In [8]:
#Подключаем библиотеки
import numpy as np
import pandas as pd

#Читаем данные из файла
df=pd.read_csv("https://raw.githubusercontent.com/junaart/ForStudents/master/Big_Data/Seminar_4/data_1.csv",delimiter=",")

#Отображаем данные
display(df)

,ФИО,Дата рождения,Пол,Дата приема на работу,Оклад,Семейное положение,Кол-во детей
0,Алистратов А.А.,27.10.1975,м,08.09.1997,4000,женат,1.0
1,Анохин Н.И.,11.12.1948,м,23.05.1986,5000,разведен,1.0
2,Антонова И.П.,04.12.1951,ж,09.05.1988,4300,замужем,1.0
3,Артемова Г.А.,06.08.1979,ж,05.09.1997,4500,незамужем,NaN
4,Афоничева Л.К.,09.01.1952,ж,05.10.1985,4900,замужем,1.0
...,...,...,...,...,...,...,...
95,Шафеева Н.К.,29.07.1939,ж,09.12.1985,4500,замужем,1.0
96,Шиманюк Н.И.,06.11.1979,м,23.11.1998,4000,холост,NaN
97,Элиава Т.М.,19.05.1981,м,10.09.1997,3700,холост,NaN
98,Якимова Н.М.,16.05.1973,ж,07.09.1999,3000,замужем,2.0
99,Яфарова Т.Н.,04.09.1945,ж,21.03.1986,4000,замужем,2.0

In [9]:
#Cформировать два отдельных DataFrame из мужчин и женщин. Для женщин рассчитать и добавить в соответствующий DataFrame столбец возраста. Для мужчин рассчитать и добавить в соответствующий DataFrame столбец стажа.

#Преобразуем даты из строчного типа в тип datetime
df['Дата приема на работу'] = pd.to_datetime(df['Дата приема на работу'], format='%d.%m.%Y')
df['Дата рождения'] = pd.to_datetime(df['Дата рождения'], format='%d.%m.%Y')
#Задаём сегодняшний день
today = pd.Timestamp.today()

#Новый датафрейм в зависимости от пола
df_male = df[df['Пол'] == 'м']
#Создаём новый столбец "Стаж". Вычитаем из сегодняшнего дня столбец 'Дата приема на работу', и записываем в формате года
df_male = df_male.assign(Experience = (today - df_male['Дата приема на работу']).astype('<m8[Y]'))
display(df_male)

,ФИО,Дата рождения,Пол,Дата приема на работу,Оклад,Семейное положение,Кол-во детей,Experience
0,Алистратов А.А.,1975-10-27,м,1997-09-08,4000,женат,1.0,25.0
1,Анохин Н.И.,1948-12-11,м,1986-05-23,5000,разведен,1.0,36.0
6,Ахундов О.Т.,1967-05-01,м,1986-05-23,4400,холост,NaN,36.0
8,Белорусец И.А.,1960-11-04,м,1989-03-09,4000,холост,NaN,33.0
10,Булгаков Ю.В.,1957-05-01,м,1985-06-09,3000,женат,1.0,37.0
13,Варлаков В.Н.,1966-10-23,м,1995-09-12,5000,холост,NaN,27.0
18,Гостев И.И.,1969-11-22,м,1996-09-13,6000,женат,2.0,26.0
20,Гринченко М.В.,1954-12-08,м,1985-09-06,4300,женат,1.0,37.0
25,Ежиков А.В.,1963-02-14,м,1990-11-01,6000,женат,4.0,32.0
27,Зайцев Б.П.,1959-08-20,м,1995-10-05,5000,женат,1.0,27.0
31,Кирюхин В.Н.,1954-08-20,м,1985-12-09,4900,женат,2.0,37.0
34,Колесников И.С.,1964-03-25,м,1985-03-05,6000,холост,NaN,37.0
41,Леонтьев В.К.,1979-01-06,м,1990-08-11,2700,холост,NaN,32.0
42,Локшин Я.С.,1961-01-17,м,1985-09-06,5000,женат,1.0,37.0
43,Львов Г.Н.,1947-07-13,м,1990-12-09,3000,женат,3.0,32.0
44,Малахов Г.И.,1954-12-08,м,1985-09-06,4300,женат,1.0,37.0
45,Марченко А.Н.,1936-10-03,м,1980-08-04,7000,женат,NaN,42.0
46,Медведев Б.М.,1960-04-24,м,1994-05-04,5600,женат,3.0,28.0
47,Мельников А.С.,1961-07-11,м,1986-03-21,5400,разведен,1.0,36.0
48,Минаев Ю.В.,1956-08-08,м,1987-12-09,3000,холост,NaN,35.0
51,Муленков Е.И.,1969-11-09,м,1992-12-20,4300,холост,1.0,30.0
55,Овчинников А.М.,1969-11-09,м,1992-12-20,4300,женат,1.0,30.0
59,Полибин А.А.,1967-05-05,м,1984-05-04,4400,женат,NaN,38.0
61,Реутенко Р.В.,1978-11-06,м,1992-12-20,4700,холост,NaN,30.0
65,Рыбальский Г.Л.,1958-10-12,м,1995-05-23,5600,женат,2.0,27.0
66,Рыжов А.В.,1958-10-12,м,1995-05-23,5600,женат,2.0,27.0
67,Сарайкин В.Ф.,1965-06-05,м,1985-06-12,4900,женат,1.0,37.0
68,Сафронов В.В.,1979-04-06,м,1998-10-08,2400,холост,NaN,24.0
69,Семенов М.П.,1970-01-09,м,1990-08-11,4700,женат,NaN,32.0
70,Скворцов С.М.,1979-04-06,м,1998-10-08,3800,холост,NaN,24.0
74,Страшнов Г.Г.,1954-02-06,м,1995-05-23,4500,женат,1.0,27.0
75,Сулдин В.Г.,1979-03-11,м,1998-10-08,3500,холост,NaN,24.0
76,Сыроватский И.В.,1977-04-25,м,1998-11-23,4400,женат,1.0,24.0
80,Устинов А.А.,1934-03-31,м,1985-06-09,4700,разведен,NaN,37.0
82,Ушкаров Н.А.,1979-11-13,м,2001-11-23,4000,холост,NaN,21.0
83,Федоров Д.М.,1932-03-31,м,1975-06-09,7700,женат,2.0,47.0
86,Фетисов А.Н.,1948-12-11,м,1986-05-23,4000,женат,1.0,36.0
92,Чернов Е.В.,1972-05-15,м,2001-09-06,5500,женат,1.0,21.0
96,Шиманюк Н.И.,1979-11-06,м,1998-11-23,4000,холост,NaN,24.0
97,Элиава Т.М.,1981-05-19,м,1997-09-10,3700,холост,NaN,25.0

In [10]:
#Новый датафрейм в зависимости от пола
df_female = df[df['Пол'] == 'ж']
#Создаём новый столбец "Возраст". Вычитаем из сегодняшнего дня столбец 'Дата рождения', и записываем в формате года
df_female = df_female.assign(Age = (today - df_female['Дата рождения']).astype('<m8[Y]'))
display(df_female)

,ФИО,Дата рождения,Пол,Дата приема на работу,Оклад,Семейное положение,Кол-во детей,Age
2,Антонова И.П.,1951-12-04,ж,1988-05-09,4300,замужем,1.0,71.0
3,Артемова Г.А.,1979-08-06,ж,1997-09-05,4500,незамужем,NaN,43.0
4,Афоничева Л.К.,1952-01-09,ж,1985-10-05,4900,замужем,1.0,71.0
5,Афоничева Л.В.,1978-06-08,ж,1998-09-22,3000,замужем,NaN,44.0
7,Бегунова С.А.,1973-05-20,ж,1997-09-11,4400,замужем,1.0,49.0
9,Бизюкова Г.П.,1957-05-01,ж,1985-06-09,4000,замужем,1.0,65.0
11,Быкова И.А.,1958-01-12,ж,1994-07-25,5600,замужем,2.0,65.0
12,Вантеева Л.В.,1958-01-12,ж,1994-07-25,4500,замужем,2.0,65.0
14,Васильева Е.Г.,1952-01-09,ж,1985-10-05,4900,замужем,1.0,71.0
15,Вуколова О.В.,1963-02-14,ж,1990-11-01,3500,замужем,2.0,60.0
16,Гаранина Г.П.,1965-06-05,ж,1985-06-12,3500,замужем,1.0,57.0
17,Гордеева Н.А.,1953-11-16,ж,1985-03-05,4100,замужем,NaN,69.0
19,Грачева О.Е.,1967-05-13,ж,2000-09-14,4500,замужем,NaN,55.0
21,Гусева И.А.,1956-06-06,ж,1987-12-09,4900,разведена,1.0,66.0
22,Дзебоева Н.А.,1954-08-20,ж,1985-12-09,4600,замужем,2.0,68.0
23,Дмитриева З.Е.,1980-09-22,ж,1998-05-09,4700,незамужем,NaN,42.0
24,Дробикова С.А.,1961-07-11,ж,1986-03-21,5600,замужем,1.0,61.0
26,Ермолаева Е.И.,1967-05-01,ж,1986-05-23,4300,незамужем,NaN,55.0
28,Зайцева Т.Н.,1980-09-22,ж,1998-05-09,3800,незамужем,NaN,42.0
29,Захарова В.В.,1964-06-24,ж,1995-09-15,4300,замужем,2.0,58.0
30,Истратова Е.Н.,1964-03-25,ж,1985-03-05,3000,замужем,2.0,58.0
32,Ковалева М.Г.,1959-08-20,ж,1995-10-05,4500,замужем,1.0,63.0
33,Колганова В.В.,1951-08-07,ж,1980-08-04,4450,замужем,1.0,71.0
35,Конюхова Л.Н.,1951-01-17,ж,1985-09-06,3000,разведена,1.0,72.0
36,Корчагина О.С.,1967-05-05,ж,1984-05-04,4400,замужем,1.0,55.0
37,Курдина С.Х.,1953-11-16,ж,1985-03-05,4100,замужем,NaN,69.0
38,Лазькова Л.В.,1978-11-06,ж,1992-12-20,4700,незамужем,NaN,44.0
39,Ларшина Н.П.,1978-12-06,ж,1997-08-08,4000,незамужем,1.0,44.0
40,Леонова Е.И.,1947-07-13,ж,1990-12-09,3000,замужем,3.0,75.0
49,Михайлова Т.В.,1954-02-06,ж,1995-05-23,3000,замужем,3.0,69.0
50,Моисеева В.Б.,1962-08-07,ж,1980-09-04,4450,замужем,2.0,60.0
52,Муравьева В.С.,1955-10-03,ж,1980-08-04,3000,незамужем,NaN,67.0
53,Нарольская Т.С.,1962-05-14,ж,1994-05-04,4000,замужем,2.0,60.0
54,Носова Л.Г.,1974-07-15,ж,1997-08-08,4300,незамужем,NaN,48.0
56,Петухова Т.Н.,1979-03-06,ж,1998-10-08,3500,незамужем,NaN,43.0
57,Пименова О.Н.,1957-09-01,ж,1990-08-11,5600,замужем,3.0,65.0
58,Позднякова Т.И.,1974-07-15,ж,1997-08-08,4300,разведена,NaN,48.0
60,Пономарева Л.А.,1945-09-04,ж,1986-03-21,4000,замужем,3.0,77.0
62,Родникова С.В.,1957-09-01,ж,1990-08-11,5600,замужем,1.0,65.0
63,Романова А.И.,1977-12-12,ж,1997-08-08,4000,незамужем,1.0,45.0
64,Романова З.В.,1974-04-06,ж,1998-11-23,4600,замужем,1.0,48.0
71,Смирнова И.В.,1948-01-02,ж,1985-11-23,5600,замужем,2.0,75.0
72,Соколова А.В.,1948-01-02,ж,1985-11-23,5600,разведена,2.0,75.0
73,Степина Т.И.,1976-12-16,ж,1997-09-05,3700,замужем,1.0,46.0
77,Туровская Н.С.,1979-05-08,ж,1997-09-05,5600,незамужем,NaN,43.0
78,Тяпкина Л.А.,1952-06-06,ж,1980-10-08,4000,замужем,NaN,70.0
79,Укладчикова Н.И.,1976-12-16,ж,1997-09-05,3700,незамужем,NaN,46.0
81,Ушакова И.И.,1979-05-06,ж,1997-09-05,5600,незамужем,NaN,43.0
84,Федорова З.А.,1952-04-02,ж,1992-09-23,4600,замужем,NaN,70.0
85,Федюшкина М.А.,1950-04-02,ж,1994-07-25,4600,замужем,1.0,72.0
87,Филатова О.В.,1942-01-21,ж,1980-11-01,4600,замужем,NaN,81.0
88,Харькова Л.В.,1980-08-23,ж,1997-09-05,4500,незамужем,NaN,42.0
89,Хромова Л.В.,1937-01-21,ж,1980-11-01,4600,замужем,NaN,86.0
90,Хромова Л.В.,1938-08-07,ж,1985-06-12,3000,замужем,1.0,84.0
91,Червякова Н.С.,1946-06-06,ж,1980-10-08,4000,замужем,NaN,76.0
93,Чигрина А.Е.,1939-07-29,ж,1985-12-09,4500,замужем,1.0,83.0
94,Чиркина А.М.,1938-08-07,ж,1985-06-12,3000,замужем,1.0,84.0
95,Шафеева Н.К.,1939-07-29,ж,1985-12-09,4500,замужем,1.0,83.0
98,Якимова Н.М.,1973-05-16,ж,1999-09-07,3000,замужем,2.0,49.0
99,Яфарова Т.Н.,1945-09-04,ж,1986-03-21,4000,замужем,2.0,77.0

In [11]:
#Отобрать только сотрудников, имеющих детей и оклад, меньше среднего оклада сотрудников.
df[(df['Кол-во детей'] > 0) & (df['Оклад'] < df['Оклад'].mean())]

,ФИО,Дата рождения,Пол,Дата приема на работу,Оклад,Семейное положение,Кол-во детей
0,Алистратов А.А.,1975-10-27,м,1997-09-08,4000,женат,1.0
2,Антонова И.П.,1951-12-04,ж,1988-05-09,4300,замужем,1.0
7,Бегунова С.А.,1973-05-20,ж,1997-09-11,4400,замужем,1.0
9,Бизюкова Г.П.,1957-05-01,ж,1985-06-09,4000,замужем,1.0
10,Булгаков Ю.В.,1957-05-01,м,1985-06-09,3000,женат,1.0
15,Вуколова О.В.,1963-02-14,ж,1990-11-01,3500,замужем,2.0
16,Гаранина Г.П.,1965-06-05,ж,1985-06-12,3500,замужем,1.0
20,Гринченко М.В.,1954-12-08,м,1985-09-06,4300,женат,1.0
29,Захарова В.В.,1964-06-24,ж,1995-09-15,4300,замужем,2.0
30,Истратова Е.Н.,1964-03-25,ж,1985-03-05,3000,замужем,2.0
35,Конюхова Л.Н.,1951-01-17,ж,1985-09-06,3000,разведена,1.0
36,Корчагина О.С.,1967-05-05,ж,1984-05-04,4400,замужем,1.0
39,Ларшина Н.П.,1978-12-06,ж,1997-08-08,4000,незамужем,1.0
40,Леонова Е.И.,1947-07-13,ж,1990-12-09,3000,замужем,3.0
43,Львов Г.Н.,1947-07-13,м,1990-12-09,3000,женат,3.0
44,Малахов Г.И.,1954-12-08,м,1985-09-06,4300,женат,1.0
49,Михайлова Т.В.,1954-02-06,ж,1995-05-23,3000,замужем,3.0
51,Муленков Е.И.,1969-11-09,м,1992-12-20,4300,холост,1.0
53,Нарольская Т.С.,1962-05-14,ж,1994-05-04,4000,замужем,2.0
55,Овчинников А.М.,1969-11-09,м,1992-12-20,4300,женат,1.0
60,Пономарева Л.А.,1945-09-04,ж,1986-03-21,4000,замужем,3.0
63,Романова А.И.,1977-12-12,ж,1997-08-08,4000,незамужем,1.0
73,Степина Т.И.,1976-12-16,ж,1997-09-05,3700,замужем,1.0
76,Сыроватский И.В.,1977-04-25,м,1998-11-23,4400,женат,1.0
86,Фетисов А.Н.,1948-12-11,м,1986-05-23,4000,женат,1.0
90,Хромова Л.В.,1938-08-07,ж,1985-06-12,3000,замужем,1.0
94,Чиркина А.М.,1938-08-07,ж,1985-06-12,3000,замужем,1.0
98,Якимова Н.М.,1973-05-16,ж,1999-09-07,3000,замужем,2.0
99,Яфарова Т.Н.,1945-09-04,ж,1986-03-21,4000,замужем,2.0

In [12]:
#Выяснить, есть ли в списке юбиляры (кому в текущем году исполнилось количество лет, оканчивающееся на нуль или пять), получить этот список в виде DataFrame.
end_of_year = pd.Timestamp(year=2024, month=1, day=1)
df_jubilee = df
df_jubilee = df_jubilee.assign(Age = (end_of_year - df_jubilee['Дата рождения']).astype('<m8[Y]'))
df_jubilee = df_jubilee[(df_jubilee['Age'] % 5 == 0) | (df_jubilee['Age'] % 10 == 0)]
display(df_jubilee)

,ФИО,Дата рождения,Пол,Дата приема на работу,Оклад,Семейное положение,Кол-во детей,Age
1,Анохин Н.И.,1948-12-11,м,1986-05-23,5000,разведен,1.0,75.0
5,Афоничева Л.В.,1978-06-08,ж,1998-09-22,3000,замужем,NaN,45.0
7,Бегунова С.А.,1973-05-20,ж,1997-09-11,4400,замужем,1.0,50.0
11,Быкова И.А.,1958-01-12,ж,1994-07-25,5600,замужем,2.0,65.0
12,Вантеева Л.В.,1958-01-12,ж,1994-07-25,4500,замужем,2.0,65.0
15,Вуколова О.В.,1963-02-14,ж,1990-11-01,3500,замужем,2.0,60.0
17,Гордеева Н.А.,1953-11-16,ж,1985-03-05,4100,замужем,NaN,70.0
25,Ежиков А.В.,1963-02-14,м,1990-11-01,6000,женат,4.0,60.0
37,Курдина С.Х.,1953-11-16,ж,1985-03-05,4100,замужем,NaN,70.0
38,Лазькова Л.В.,1978-11-06,ж,1992-12-20,4700,незамужем,NaN,45.0
39,Ларшина Н.П.,1978-12-06,ж,1997-08-08,4000,незамужем,1.0,45.0
61,Реутенко Р.В.,1978-11-06,м,1992-12-20,4700,холост,NaN,45.0
65,Рыбальский Г.Л.,1958-10-12,м,1995-05-23,5600,женат,2.0,65.0
66,Рыжов А.В.,1958-10-12,м,1995-05-23,5600,женат,2.0,65.0
71,Смирнова И.В.,1948-01-02,ж,1985-11-23,5600,замужем,2.0,75.0
72,Соколова А.В.,1948-01-02,ж,1985-11-23,5600,разведена,2.0,75.0
86,Фетисов А.Н.,1948-12-11,м,1986-05-23,4000,женат,1.0,75.0
90,Хромова Л.В.,1938-08-07,ж,1985-06-12,3000,замужем,1.0,85.0
94,Чиркина А.М.,1938-08-07,ж,1985-06-12,3000,замужем,1.0,85.0
98,Якимова Н.М.,1973-05-16,ж,1999-09-07,3000,замужем,2.0,50.0

In [13]:
#Получить DataFrame, в котором рассчитывается количество сотрудников по категориям: женат, замужем, холост, незамужем, разведен, разведена.
df['Семейное положение'] = df['Семейное положение'].astype('category')
ser_family = df['Семейное положение'].value_counts()
df_family = pd.DataFrame({'Семейное положение':ser_family.index, 'Количество':ser_family.values})
display(df_family)

  Семейное положение  Количество
0            замужем          42
1              женат          23
2          незамужем          14
3             холост          14
4          разведена           4
5           разведен           3

In [14]:
#Полученный DataFrame сохранить в формате csv
df_family.to_csv('Семейное_положение.csv')